model_list:
  - model_name: openai
    litellm_params:
      model: openai/{{OPENAI_MODEL}}
      api_base: {{OPENAI_API_BASE}}
      api_key: {{OPENAI_API_KEY}}

litellm_settings:
  set_verbose: true
  drop_params: true
  enable_mcp: true

general_settings:
  master_key: {{LITELLM_MASTER_KEY}}

mcp_servers:
  mcp_tools:
    url: {{MCP_SERVER_URL}}
    transport: "http"
    description: "Internal MCP tools"
    headers:
      Authorization: "Bearer {{MCP_API_KEY}}"